# Site settings
name: ehlxr
location: 北京
company: 新奥集团来康科技
position: Java 高级工程师
github: https://github.com/ehlxr
twitter: https://www.twitter.com/ehlxr
phone: 1580424XXXX
email: xxxx@gmail.com

baseurl: ""

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

